"""Constants for Hermes Assist."""

from __future__ import annotations

DOMAIN = "hermes_assist"

PLATFORMS = ["conversation", "stt", "tts"]

CONF_BASE_URL = "base_url"
CONF_VOICE_BASE_URL = "voice_base_url"
CONF_API_TOKEN = "api_token"
CONF_ENABLE_CONVERSATION = "enable_conversation"
CONF_ENABLE_STT = "enable_stt"
CONF_ENABLE_TTS = "enable_tts"
CONF_HEALTH_PATH = "health_path"
CONF_CAPABILITIES_PATH = "capabilities_path"
CONF_MODEL = "model"
CONF_CONVERSATION_API = "conversation_api"
CONF_CONVERSATION_PATH = "conversation_path"
CONF_CHAT_COMPLETIONS_PATH = "chat_completions_path"
CONF_STT_PATH = "stt_path"
CONF_STT_PROVIDER = "stt_provider"
CONF_STT_BASE_URL = "stt_base_url"
CONF_STT_API_TOKEN = "stt_api_token"
CONF_STT_MODEL = "stt_model"
CONF_STT_RESPONSE_TEXT_FIELD = "stt_response_text_field"
CONF_TTS_PATH = "tts_path"
CONF_TTS_PROVIDER = "tts_provider"
CONF_TTS_BASE_URL = "tts_base_url"
CONF_TTS_API_TOKEN = "tts_api_token"
CONF_TTS_MODEL = "tts_model"
CONF_TTS_VOICE = "tts_voice"
CONF_TIMEOUT = "timeout_seconds"
CONF_DEFAULT_LANGUAGE = "default_language"
CONF_TTS_AUDIO_FORMAT = "tts_audio_format"

DEFAULT_HEALTH_PATH = "/health"
DEFAULT_CAPABILITIES_PATH = "/v1/capabilities"
DEFAULT_MODEL = "hermes-agent"
DEFAULT_CONVERSATION_API = "responses"
DEFAULT_CONVERSATION_PATH = "/v1/responses"
DEFAULT_CHAT_COMPLETIONS_PATH = "/v1/chat/completions"
DEFAULT_VOICE_BASE_URL = "http://localhost:8765"
DEFAULT_STT_PATH = "/ha/v1/audio/transcriptions"
DEFAULT_STT_PROVIDER = "hermes_plugin"
DEFAULT_STT_BASE_URL = "http://localhost:8765"
DEFAULT_STT_MODEL = "whisper-1"
DEFAULT_STT_RESPONSE_TEXT_FIELD = "text"
DEFAULT_TTS_PATH = "/ha/v1/audio/speech"
DEFAULT_TTS_PROVIDER = "hermes_plugin"
DEFAULT_TTS_BASE_URL = "http://localhost:8765"
DEFAULT_TTS_MODEL = "gpt-4o-mini-tts"
DEFAULT_TTS_VOICE = "alloy"
DEFAULT_TIMEOUT = 120
DEFAULT_LANGUAGE = "en"
DEFAULT_TTS_AUDIO_FORMAT = "mp3"

STORAGE_CLIENT = "client"
